-- Script de criação do Banco de Dados Firebird
-- Tabelas
CREATE TABLE CLIENTE (
    CODIGO INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(60),
    UF VARCHAR(2),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUTO (
    CODIGO INTEGER NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO_VENDA NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);

CREATE TABLE PEDIDO (
    NUMERO_PEDIDO INTEGER NOT NULL,
    DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CODIGO_CLIENTE INTEGER NOT NULL,
    VALOR_TOTAL NUMERIC(15,2) NOT NULL,
    OBSERVACAO VARCHAR(200),
    CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO)
);

CREATE TABLE PEDIDO_ITEM (
    ID INTEGER NOT NULL,
    NUMERO_PEDIDO INTEGER NOT NULL,
    CODIGO_PRODUTO INTEGER NOT NULL,
    QUANTIDADE NUMERIC(15,3) NOT NULL,
    VLR_UNITARIO NUMERIC(15,2) NOT NULL,
    VLR_TOTAL NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_PEDIDO_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO_ITEM_PEDIDO FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDO(NUMERO_PEDIDO) ON DELETE CASCADE,
    CONSTRAINT FK_PEDIDO_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO)
);

-- Generators / Sequences
CREATE SEQUENCE GEN_PEDIDO_ID;
CREATE SEQUENCE GEN_PEDIDO_ITEM_ID;

-- Triggers para Auto Incremento (opcional se usar Identity no Firebird 3+, mas comum em versões anteriores)
SET TERM ^ ;
CREATE TRIGGER TRG_PEDIDO_BI FOR PEDIDO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.NUMERO_PEDIDO IS NULL) THEN
    NEW.NUMERO_PEDIDO = NEXT VALUE FOR GEN_PEDIDO_ID;
END^

CREATE TRIGGER TRG_PEDIDO_ITEM_BI FOR PEDIDO_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_PEDIDO_ITEM_ID;
END^
SET TERM ; ^

-- Índices
CREATE INDEX IDX_PEDIDO_CLIENTE ON PEDIDO(CODIGO_CLIENTE);
CREATE INDEX IDX_PEDIDO_ITEM_PEDIDO ON PEDIDO_ITEM(NUMERO_PEDIDO);
CREATE INDEX IDX_PEDIDO_ITEM_PRODUTO ON PEDIDO_ITEM(CODIGO_PRODUTO);

-- Carga Inicial de Dados (Clientes)
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (1, 'Consumidor Final', 'Sao Paulo', 'SP');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (2, 'Joao Silva', 'Rio de Janeiro', 'RJ');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (3, 'Maria Oliveira', 'Belo Horizonte', 'MG');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (4, 'Empresa ABC Ltda', 'Curitiba', 'PR');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (5, 'Jose Santos', 'Porto Alegre', 'RS');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (6, 'Ana Paula', 'Salvador', 'BA');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (7, 'Carlos Pereira', 'Fortaleza', 'CE');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (8, 'Fernanda Costa', 'Recife', 'PE');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (9, 'Ricardo Almeida', 'Manaus', 'AM');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (10, 'Juliana Souza', 'Brasilia', 'DF');

-- Carga Inicial de Dados (Produtos)
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (1, 'Arroz 5kg', 25.50);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (2, 'Feijao Carioca 1kg', 8.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (3, 'Oleo de Soja 900ml', 7.45);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (4, 'Acucar Refinado 1kg', 4.20);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (5, 'Cafe Torrado 500g', 18.30);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (6, 'Macarrao Espaguete 500g', 3.75);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (7, 'Leite Integral 1L', 5.60);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (8, 'Detergente Liquido 500ml', 2.15);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (9, 'Sabonete em Barra 90g', 1.85);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (10, 'Creme Dental 90g', 4.50);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (11, 'Papel Higienico c/ 4', 6.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (12, 'Sabao em Po 1kg', 12.40);
